name: 'php'

on:
  pull_request:
    paths:
      - '**/*.php'
      - '.github/workflows/php.yml'
      - '**/composer.json'
  push:
    paths:
      - '**/*.php'
      - '.github/workflows/php.yml'
      - '**/composer.json'

jobs:
  cs:
    uses: bedita/github-workflows/.github/workflows/php-cs.yml@v2
    with:
      php_versions: '["7.4","8.1","8.2"]'

  stan:
    uses: bedita/github-workflows/.github/workflows/php-stan.yml@v2
    with:
      php_versions: '["7.4","8.1","8.2"]'

  unit-4:
    uses: bedita/github-workflows/.github/workflows/php-unit.yml@v2
    with:
      php_versions: '["7.4","8.1","8.2"]'
      bedita_version: '4.7.1'

  unit-5:
    uses: bedita/github-workflows/.github/workflows/php-unit.yml@v2
    with:
      php_versions: '["7.4","8.1","8.2"]'
      bedita_version: '5.0.2'
